/**
 * Chrysanthemum — static file server.
 *
 * Serves the pages generated by build.py. Deliberately small: no framework, no
 * dependencies, nothing to keep up to date.
 *
 *   PORT=8787 bun run server.ts
 */

import { resolve, join, extname, sep } from "node:path";
import { statSync } from "node:fs";

const ROOT = resolve(import.meta.dir);
const PORT = Number(process.env.PORT ?? 8787);
const HOST = process.env.HOST ?? "127.0.0.1";

/** Assets are content-addressed by rebuild, so cache HTML briefly and the rest longer. */
const CACHE = {
  html: "public, max-age=60",
  asset: "public, max-age=3600",
};

/**
 * Map a request path to a file inside ROOT, or null if it escapes or is missing.
 * Tries, in order: the literal path, path + ".html", and path + "/index.html",
 * so /about and /s/mo-li-hua work without the extension.
 */
function resolveFile(pathname: string): string | null {
  let decoded: string;
  try {
    decoded = decodeURIComponent(pathname);
  } catch {
    return null; // malformed percent-encoding
  }

  if (decoded.includes("\0")) return null;

  const candidates =
    decoded === "/" || decoded === ""
      ? ["index.html"]
      : [decoded.slice(1), `${decoded.slice(1)}.html`, join(decoded.slice(1), "index.html")];

  for (const rel of candidates) {
    const full = resolve(ROOT, rel);

    // Containment check: must sit inside ROOT, not merely share its prefix.
    if (full !== ROOT && !full.startsWith(ROOT + sep)) continue;

    try {
      if (statSync(full).isFile()) return full;
    } catch {
      // not there, try the next candidate
    }
  }
  return null;
}

function notFound(): Response {
  const body = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Not found — Chrysanthemum</title>
<link rel="stylesheet" href="/assets/style.css"></head>
<body><main class="wrap"><section class="prose" style="padding-top:4rem">
<h1>&#10045; Not found</h1>
<p>That page isn't here. <a href="/">Back to the songs</a>.</p>
</section></main></body></html>`;
  return new Response(body, {
    status: 404,
    headers: { "content-type": "text/html; charset=utf-8" },
  });
}

const server = Bun.serve({
  port: PORT,
  hostname: HOST,

  fetch(req) {
    const { pathname } = new URL(req.url);

    if (req.method !== "GET" && req.method !== "HEAD") {
      return new Response("Method not allowed", {
        status: 405,
        headers: { allow: "GET, HEAD" },
      });
    }

    const file = resolveFile(pathname);
    if (!file) return notFound();

    const isHtml = extname(file) === ".html";
    return new Response(Bun.file(file), {
      headers: {
        "cache-control": isHtml ? CACHE.html : CACHE.asset,
        "x-content-type-options": "nosniff",
      },
    });
  },

  error() {
    return new Response("Internal server error", { status: 500 });
  },
});

console.log(`chrysanthemum serving ${ROOT} on http://${server.hostname}:${server.port}`);
